### ISSUE TITLE
Header-Navigation

### ISSUE THREAD

**Issue by LuFass** [Jackson085/Software-Engineering-1#51]
Header fürs Frontend bauen

**Comment by NiklasHintemann** [comment]
Änderungsvorschläge:
1. Aktiver Button anderes OnHover design. Vorschlag durch den Status activeTab eine ngClass die je nach Status button primary oder button primary-alt setzt.
2. Aktuell wird das aktive design bei persönliche Mappe erst beim zweiten Click gesetzt.
3. Die Icon in der Farbe primary anzeigen und bei dem Status active in white. Vorschlag: fortawesome-free habe ich bereits für die loin Komponente eingebunden. Die haben gute Icons.
`<i [ngClass]="isPasswordVisible() ? 'fa fa-eye-slash' : 'fa fa-eye'"></i>`
